name: Swift Vapor CI/CD

on:
  push:
    branches:
      - main  # 更改为你的默认分支，例如master或main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up swiftenv
      run: git clone https://github.com/kylef/swiftenv.git ~/.swiftenv

    - name: Setup environment
      run: |
        export SWIFTENV_ROOT="$HOME/.swiftenv"
        export PATH="$SWIFTENV_ROOT/bin:$PATH"
        eval "$(swiftenv init -)"
        echo "$PATH" >> $GITHUB_PATH
        echo $SWIFTENV_ROOT

    - name: Install Swift
      run: |
        swiftenv install 5.8.1 --skip-existing
        swiftenv global 5.8.1

    - name: Build Swift Project 
      run: |
        swift build -c release --static-swift-stdlib

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: vapor-app-artifact
        path: |
          .build/x86_64-unknown-linux-gnu/release/App
          Public
          Resources

