name: Swift Vapor CI/CD with Docker

on:
  push:
    branches:
      - main  # 更改为你的默认分支，例如master或main

env:
  SWIFTENV_ROOT: $HOME/.swiftenv
  PATH: ${{ env.SWIFTENV_ROOT }}/bin:${{ env.SWIFTENV_ROOT }}/shims:${{ env.PATH }}


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Swift
      run: |
        git clone https://github.com/kylef/swiftenv.git ~/.swiftenv
        echo 'export SWIFTENV_ROOT="$HOME/.swiftenv"' >> $GITHUB_ENV
        echo 'export PATH="$SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH"' >> $GITHUB_ENV
        echo 'eval "$(swiftenv init -)"' >> $GITHUB_ENV


    - name: Build Swift Project 
      run: |
       swift build -c release


    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: vapor-app-artifact
        path: |
          .build/release/App
          Public
          Resources

