name: Swift Vapor Multi-Arch CI/CD

on:
  push:
    branches: [dev, main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]  # 并行构建两种架构
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Docker 构建环境
        run: |
          docker run --rm --platform linux/${{ matrix.arch }} \
            -v "$PWD:/app" -w /app \
            swift:5.9-jammy \
            swift build -c release --static-swift-stdlib
          
          # 重命名二进制文件以区分架构
          mv .build/release/App ./App-${{ matrix.arch }}

      - name: 收集产物
        run: |
          mkdir -p release
          mv App-${{ matrix.arch }} release/
          cp -r Public Resources release/
          cd release && zip -r ../vapor-app-${{ matrix.arch }}.zip .

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: vapor-app-${{ matrix.arch }}
          path: vapor-app-${{ matrix.arch }}.zip

  # 可选：合并两个架构的产物（需添加后续步骤）
  # package:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/download-artifact@v4
  #       with:
  #         pattern: vapor-app-*
  #     - run: mkdir universal-release && unzip vapor-app-*.zip -d universal-release
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: vapor-app-universal
  #         path: universal-release


    # - name: 上传产物
    #   uses: appleboy/scp-action@v0.1.4
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     password: ${{ secrets.PASSWORD }}
    #     port: ${{ secrets.PORT }}
    #     source: output_filename.zip
    #     target: ${{secrets.TARGET_FOLD}}

    # - name: 部署服务
    #   uses: appleboy/ssh-action@v1.0.0
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     password: ${{ secrets.PASSWORD }}
    #     port: ${{ secrets.PORT }}
    #     script: |
    #       cd ${{secrets.TARGET_FOLD}}
    #       ls -all
    #       unzip -o output_filename.zip
    #       chmod +x App
    #       supervisorctl stop iblog-oldbird-run
    #       supervisorctl start iblog-oldbird-run
         



