name: Swift Vapor CI/CD

on:
  push:
    branches:
      - main  # 更改为你的默认分支，例如master或main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: 拉取代码
      uses: actions/checkout@v3
    
    - name: 安装 SwiftEnv
      run: git clone https://github.com/kylef/swiftenv.git ~/.swiftenv

    - name: Setup environment
      run: |
        export SWIFTENV_ROOT="$HOME/.swiftenv"
        export PATH="$SWIFTENV_ROOT/bin:$PATH"
        eval "$(swiftenv init -)"
        echo "$PATH" >> $GITHUB_PATH
        echo $SWIFTENV_ROOT

    - name: 安装Swift
      run: |
        swiftenv install 5.8.1 --skip-existing
        swiftenv global 5.8.1

    - name: 编译项目
      run: |
        swift build -c release --static-swift-stdlib
        mv .build/x86_64-unknown-linux-gnu/release/App ./
        chmod +x ./App


    - name: 保存编译的包
      uses: actions/upload-artifact@v2
      with:
        name: vapor-app-artifact
        path: |
          App
          Public
          Resources

    - name: 收集产物
      run: |
        mkdir -p dirs
        mv App dirs/
        mv Public dirs/
        mv Resources dirs/

    - name: 上传产物
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "dirs/"
        target: "/www/wwwroot/iblog.oldbird.run/"

    - name: 部署服务
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /www/wwwroot/iblog.oldbird.run/
          ls -all
          chmod +x App
          supervisorctl stop iblog-oldbird-run
          supervisorctl start iblog-oldbird-run
         



